"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
        1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. 
Note: Your code should return a result within 10 seconds.
"""
import time

def findEvenFibonacciSum():
		number1=1
		number2=0
		number3=sum=counter=0
		while number3<4000000:
			number3=number1+number2
			if number3 % 2 == 0:
				sum+=number3
			number1=number2
			number2=number3
			counter+=1
		print("Sum: "+str(sum))
	
start=time.time()
findEvenFibonacciSum()
end=time.time()
print(f"Runtime of the program is {end - start}")